### ISSUE TITLE
issues for auto-extended

### ISSUE THREAD

**Issue by brt-wu-jian** [userpro/MemoryPool#11]
I think the extended feature has problem:
![image](https://user-images.githubusercontent.com/68941252/160552369-1288f8e9-0acf-4f8c-9f9c-151d92aa86c4.png)
In above code, why compare with the value mem_pool_size? 
max_mem_pool_size should be used instead here in my opinion.

Another place is:
![image](https://user-images.githubusercontent.com/68941252/160552988-f2bae009-c38d-48e8-8fdf-9fd2cb14c50b.png)

In my opinion, it should be modified as below:
![image](https://user-images.githubusercontent.com/68941252/160553086-3cd780d9-4d81-4487-b2c9-9c1a9c4a911c.png)

Please correct me if my understanding is wrong.

Type Chinese is also okay for me. 

Thank you.

**Comment by userpro** [comment]
这俩个点都在于 mempool_size 是个常量，我新增点注释说明一下
