### ISSUE TITLE
申请内存不能释放

### ISSUE THREAD

**Issue by haiwen007** [userpro/MemoryPool#18]
![image](https://github.com/user-attachments/assets/5807eee3-851e-4f56-a47a-1514d5a4186c)

![image](https://github.com/user-attachments/assets/633743c6-957a-4d69-8cc0-2ea4fb80a0a0)

参考示例：
1. 给结构体申请内存
2. 给结构体中变量申请内存

问题：
1. 不能单独释放结构体变量空间？
2. 必须通过 MemoryPoolDestroy 才可以释放内存？
3. 图片3 这样操作，还有段错误...

**Comment by haiwen007** [comment]
![image](https://github.com/user-attachments/assets/635b5d82-66ae-4e35-8105-bb45b095e4f1)

**Comment by userpro** [comment]
1. 可以的
2. 是的，destroy才能真实释放
3. 27行应该是sdata1，这么写把内存写坏了
