### ISSUE TITLE
关于释放内存报错

### ISSUE THREAD

**Issue by 791136190** [userpro/MemoryPool#5]
如果释放的内存为**第一块申请出来的内存**，在使用自动扩展后，在释放时：merge_free_chunk函数中，Chunk *p0 = *(Chunk **)((char *)c - CHUNKEND), *p1 = c;
	while ((char *)p0 >= mm->start && p0->is_free)
{
.........
}
c操作任然会获取到错误的地址。
建议增加每个管理数据段的结束地址校验，比如
while ((char *)p0 >= mm->start && ****(char *)p0 < mm->end**** && p0->is_free)
end在每次调用系统malloc的时候进行记录

**Comment by 791136190** [comment]
另外，关于新申请内存大于初始化内存段大小会导致系统内存全被申请掉的问题，建议可以这样修改：		if (mp->mem_pool_size - mm->alloc_mem < total_size)
		{
			if (0 == mm->alloc_mem)
			{
				fprintf(stderr, "your mem pool size is too small[%zd VS %zd]\n", mp->mem_pool_size, total_size);
				mp->mem_pool_size = total_size * 2;
			}
			mm = mm->next;
			continue;
		}
但是这样在释放的时候需要进行调整

**Comment by userpro** [comment]
已更新 暂时不打算增加自动调整大小的功能
