### ISSUE TITLE
大哥，我用了你的代码，内存释放报错

### ISSUE THREAD

**Issue by happyantlau** [userpro/MemoryPool#6]
大哥 help 代码有毒

**Comment by userpro** [comment]
报错信息环境贴一下

**Comment by happyantlau** [comment]
openmp里面用了




| |
刘哲源
邮箱：allenliuvip@163.com
|

签名由 网易邮箱大师 定制

在2018年06月20日 14:59，Zheng 写道：

报错信息环境贴一下

**Comment by userpro** [comment]
不支持多线程哦 如果能有详细点的错误信息可以帮助我修改哦

**Comment by userpro** [comment]
不支持多线程 如果有详细点的错误信息能帮助定位下 多谢了
