### ISSUE TITLE
在调用get_mempool_usage方法时，突然返回一个很大的值

### ISSUE THREAD

**Issue by wangzhenhua92429** [userpro/MemoryPool#7]
你好：
        关注和使用你的项目一段时间了，感谢你的分享，给我们带来了便利！
        但是，我们在使用的过程中，通过get_mempool_usage方法获取使用率，一直能正确获取，但是有时会突然返回一个很大的值，由于是个异常，不太好抓，但是真的出现了！我找了一段时间没找到原因，不知道你是否有时间看看！（我用在嵌入式Linux上）

**Comment by userpro** [comment]
使用的是最新的代码吗？


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by wangzhenhua92429** [comment]
不是最新的，应该差不多几个月之前，你之前碰见过这种情况？

**Comment by userpro** [comment]
嗯 更新到最新的代码
